
export const colorFuncs = [
    "red",
    "black",
    "blackBright",
    "blue",
    "blueBright",
    "bold",
    "cyanBright",
    "gray",
    "green",
    "greenBright",
    "grey",
    "italic",
    "magenta",
    "magentaBright",
    "overline",
    "redBright",
    "reset",
    "strikethrough",
    "underline",
] as const;
